#conda env create -f environment.yml
name: py-go-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  #- tesseract
  #- go
  - pip:
    - matplotlib
    - pandas
    - tensorflow
    #- keras
    #- opencv-contrib-python==3.4.5.20
    - opencv-python
    #- pytesseract
    - scipy
    - sklearn
    #- dtw
    #- fastdtw
